apiVersion: v1
kind: ConfigMap
metadata:
  name: config-example
  namespace: default
data:
  application.yml: |-
    welcome:
      message: Hello Spring Cloud from application.yml
    message: Hi from application.yml