apiVersion: v1
kind: ConfigMap
metadata:
  name: config-example
  namespace: default
data:
  application.properties: |-
    welcome.message=Hello Spring Cloud from application.properties
    message=Hi from application.properties
