apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    dateTime:
      format: "2020-05-13_13-13-32.999_MST"
      timezone: "Local"
  artifacts:
    - image: atropos0116/config-example
      docker:
        dockerfile: Dockerfile
  local: {}

deploy:
  kubectl:
    manifests:
      - config.yaml
      - deploy.yaml
