apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: atropos0116/config-example
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.java
            dest: .
  local: {}

deploy:
  kubectl:
    manifests:
      - config.yaml
      - deploy.yaml
