logging.level.org.springframework.cloud.kubernetes: DEBUG
spring.application.name: config-example

management:
  endpoints:
    restart:
      enabled: true
    web:
      exposure:
        include: info,refresh,keepalive,health